Style/StringLiterals:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: leading
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
  Enabled: true

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Style/NumericPredicate:
  Enabled: false

Naming/PredicateName:
  Enabled: false
